# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2016
  project: Tag Cloud ExtBase (Français)
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - pits_tagcloud.tex
    - Tag Cloud ExtBase
    - Minu Thomas
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
