<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_tagcloud"
 *
 * Auto generated by Extension Builder 2016-04-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pits Tag Cloud',
	'description' => 'An extension to generate tagcloud from manual link tags or from table entries',
	'category' => 'plugin',
	'author' => 'Minu Thomas',
	'author_email' => 'minu.ts@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);