<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_tagcloud"
 *
 * Auto generated by Extension Builder 2016-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pits Tag Cloud',
	'description' => 'An extension to generate tagcloud out of text links, image links or table data',
	'category' => 'plugin',
	'author' => 'Minu Thomas',
	'author_email' => 'minu.ts@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);